#!/bin/sh
#
# unipass: Browser independent password manager
#
# Dependencies: amenu/dmenu/rofi, gnupg, xsel & xdotool
#
# Environment Variable: DMENU, GPG_MAIL, UNIPASS_SOURCE
#
# Usage: unipass add|fetch

prompt() { : | $DMENU -p "$1" || exit 0; }

gpg -d "$UNIPASS_SOURCE".gpg > "$UNIPASS_SOURCE"

trap 'rm -f $UNIPASS_SOURCE' HUP EXIT

case $1 in
    a*)
        account=$(prompt "Account")
        [ -z "$account" ] && exit 1
        name=$(prompt "Name")
        [ -z "$name" ] && exit 1
        pass=$(prompt "Pass")
        if [ -z "$pass" ]; then
            pass=$(gpg --gen-random --armor 1 12)
            echo "$pass" | xsel -b
        fi

        echo "$account,$name,$pass" >> "$UNIPASS_SOURCE"
        rm "$UNIPASS_SOURCE".gpg
        gpg -esr "$GPG_MAIL" "$UNIPASS_SOURCE"
        ;;
    f*)
        account=$(
            while IFS= read -r line; do
                i=$((i + 1))
                [ $i = 1 ] && continue
                echo "${line%%,*}"
            done < "$UNIPASS_SOURCE" | $DMENU || exit 0
        )
        [ -z "$account" ] && exit 1

        while IFS= read -r line; do
            if [ "${line%%,*}" = "$account" ]; then
                name_n_pass=${line#*,}
                name="${name_n_pass%,*}"
                pass="${name_n_pass#*,}"

                # echo "$name" | xsel -b
                # xdotool key Control+v
                xdotool type "$name"

                xdotool key Tab
                echo "$pass" | xsel -b
                # xdotool key Control+v
            fi
        done < "$UNIPASS_SOURCE"
        ;;
esac
