#!/bin/sh
#
# unipass: Browser independent password manager
#
# Dependencies: amenu/dmenu/rofi, gnupg, wl-clipboard & ydotool
#
# Environment Variable: DMENU, GPG_MAIL, UNIPASS_SOURCE
#
# Usage: unipass add|fetch

prompt() { : | $DMENU -p "$1" || exit 0; }

case $1 in
    a*)
        account=$(prompt "Account")
        [ -z "$account" ] && exit 1
        name=$(prompt "Name")
        [ -z "$name" ] && exit 1
        pass=$(prompt "Pass")
        if [ -z "$pass" ]; then
            pass=$(gpg --gen-random --armor 1 12)
            echo "$pass" | xsel -b
            echo "$pass" | wl-copy
        fi
        echo "$account,$name,$pass" >> "$UNIPASS_SOURCE"
        ;;
    f*)
        account=$(
            while IFS= read -r line; do
                i=$((i + 1))
                [ $i = 1 ] && continue
                echo "${line%%,*}"
            done < "$UNIPASS_SOURCE" | $DMENU || exit 0
        )
        [ -z "$account" ] && exit 1

        while IFS= read -r line; do
            if [ "${line%%,*}" = "$account" ]; then
                name_n_pass=${line#*,}
                name="${name_n_pass%,*}"
                pass="${name_n_pass#*,}"

                ydotool type "$name"
                #  xdotool key Tab
                echo "$pass" | xsel -b
                echo "$pass" | wl-copy
            fi
        done < "$UNIPASS_SOURCE"
        ;;
esac
