#!/bin/sh
#
# unipass: Browser independent password manager
#
# Dependencies: amenu/dmenu/rofi, gnupg, xsel & xdotool
#
# Usage: unipass add|fetch

#===============================================================================
#                             Config
#===============================================================================

GPG_MAIL=salmanabedin@disroot.org
PASSWORD_PATH=$GIT/own/magpie-private/.local/share/passwords
DMENU=amenu

#===============================================================================
#                             Script
#===============================================================================

prompt() { : | $DMENU -p "$1" || kill $$; }

case $1 in
   a*)
      ACCOUNT=$(prompt "Account")
      [ -z "$ACCOUNT" ] && exit 1
      NAME=$(prompt "Name")
      [ -z "$NAME" ] && exit 1
      PASS=$(prompt "Pass")
      if [ -z "$PASS" ]; then
         PASS=$(gpg --gen-random --armor 1 15)
         echo "$PASS" | xsel -b
      fi
      FILE=$PASSWORD_PATH/"$ACCOUNT"
      echo "$NAME,$PASS" > "$FILE"
      gpg -esr $GPG_MAIL "$FILE"
      rm "$FILE"
      ;;
   f*)
      ACCOUNT=$(
         for file in "$PASSWORD_PATH"/*.gpg; do
            TRIMMED_LEAD_ONLY=${file##*/}
            TRIMMED_LEAD_TRAIL=${TRIMMED_LEAD_ONLY%.*}
            echo "$TRIMMED_LEAD_TRAIL"
         done | $DMENU || kill $$
      )
      [ -z "$ACCOUNT" ] && exit 1

      FILE=$PASSWORD_PATH/$ACCOUNT
      NAME_PASS=$(gpg -d "$FILE".gpg)
      NAME=${NAME_PASS%%,*}
      PASS=${NAME_PASS#*,}
      echo "$NAME" | xsel -b
      xdotool key Control+v
      xdotool key Tab
      echo "$PASS" | xsel -b
      rm "$FILE"
      ;;
esac
