#!/bin/sh
#
# unipass: Browser independent password manager
#
# Dependencies: dmenu/rofi, gnupg, xsel & xdotool
#
# Usage: unipass add|fetch

#===============================================================================
#                             Config
#===============================================================================

GPG_MAIL=salmanabedin@disroot.org
PASSWORD_PATH=$GIT/own/magpie-private/.local/share/passwords
DMENU=dmenu

#===============================================================================
#                             Script
#===============================================================================

case $1 in
   a*)
      ACCOUNT=$(: | $DMENU -p "Account") &&
         NAME=$(: | $DMENU -p "Name") &&
         PASS=$(: | $DMENU -p "Pass") && {
         #PASS=$(gpg --gen-random --armor 1 15)
         #echo "$PASS" | xsel -b
         FILE=$PASSWORD_PATH/"$ACCOUNT"
         echo "$NAME,$PASS" > "$FILE"
         gpg -esr $GPG_MAIL "$FILE"
         rm "$FILE"
      }
      ;;
   f*)
      ACCOUNT=$(
         for file in "$PASSWORD_PATH"/*.gpg; do
            TRIMMED_LEAD=${file##*/}
            TRIMMED_TRAIL=${TRIMMED_LEAD%.*}
            echo "$TRIMMED_TRAIL"
         done | $DMENU
      ) && {
         FILE=$PASSWORD_PATH/$ACCOUNT
         NAME_PASS=$(gpg -d "$FILE".gpg)
         NAME=${NAME_PASS%%,*}
         PASS=${NAME_PASS#*,}
         echo "$NAME" | xsel -b
         xdotool key Control+v
         xdotool key Tab
         echo "$PASS" | xsel -b
         rm "$FILE"
      }
      ;;
esac
